### ISSUE TITLE
"We were unable to process your request. Sorry about that."

### ISSUE THREAD

**Issue by Viktini** [GeorgeSG/sub.rehab#22] opened 2023-07-19 11:43 UTC
Was trying to add r/deadmau5's Discord from their sidebar, and got that error.

The console output I've got:
`{"code":"failed-precondition","name":"FirebaseError"} `

`[{"update":{"name":"projects//databases/(default)/documents/linkSubmissions/mm2Ei8l6ro9tJ4ajhkyx","fields":{"subreddit":{"stringValue":"r/deadmau5"},"service":{"stringValue":"discord"},"link":{"stringValue":"https://discord.gg/RMbVS8R"},"official":{"booleanValue":true},"officialExplanation":{"stringValue":"From the sidebar on r/deadmau5. They also link mau5trap's official mau5cord server."},"sent_at":{"timestampValue":"2023-07-19T11:41:04.852000000Z"}}},"currentDocument":{"exists":false}}]}`

`FirebaseError: Request failed with error: Invalid resource field value in the request.`

If it's because it already exists, it's probably worth to let the user know about that.

**Comment by GeorgeSG** [comment] 2023-07-19 14:02
Thanks for the bug report! I can confirm I'm reproducing this as well. 

This is probably due to some changes I made around the lemmy/discord statistics. I'll take a look tonight and try to fix this :)

**Comment by GeorgeSG** [comment] 2023-07-19 18:23
@Viktini thanks for reporting! Issue should be fixed now, can you try submitting one more time?

Thank you!

**Closed by GeorgeSG** 2023-07-19 18:23 UTC
Labels: bug

**Comment by Viktini** [comment] 2023-07-19 20:52
Sorry I'm late but yup! It worked!
